export const activityMock = [
  {
    id: 0,
    start: new Date(2023, 2, 25, 14, 45, 0),
    end: new Date(2023, 2, 25, 19, 45, 0),
    text: "这是一个活动",
    name: "吃饭睡觉打豆豆",
    activityType: '类型1',
    placeID: 1,
    isPlace: true,
    isCycle: true,
    isGroup: false,
  },
  {
    id: 1,
    start: new Date(2023, 2, 25, 14, 45, 0),
    end: new Date(2023, 2, 25, 19, 45, 0),
    text: "这是一个线上活动",
    name: "吃饭睡觉打豆豆Online",
    activityType: '类型2',
    conferenceUrl: "www.baidu.com",
    isPlace: false,
    isCycle: false,
    isGroup: true, 
  },
  {
    id: 2,
    start: new Date(2023, 2, 25, 14, 45, 0),
    end: new Date(2023, 2, 25, 19, 45, 0),
    text: "这是一个活动",
    name: "吃饭睡觉打豆豆",
    activityType: '类型1',
    placeID: 1,
    isPlace: true,
    isCycle: true,
    isGroup: false,
  },
  {
    id: 3,
    start: new Date(2023, 2, 25, 14, 45, 0),
    end: new Date(2023, 2, 25, 19, 45, 0),
    text: "这是一个线上活动",
    name: "吃饭睡觉打豆豆Online",
    activityType: '类型2',
    conferenceUrl: "www.baidu.com",
    isPlace: false,
    isCycle: false,
    isGroup: true, 
  },
  {
    id: 4,
    start: new Date(2023, 2, 25, 14, 45, 0),
    end: new Date(2023, 2, 25, 19, 45, 0),
    text: "这是一个活动",
    name: "吃饭睡觉打豆豆",
    activityType: '类型1',
    placeID: 1,
    isPlace: true,
    isCycle: true,
    isGroup: false,
  },
  {
    id: 5,
    start: new Date(2023, 2, 25, 14, 45, 0),
    end: new Date(2023, 2, 25, 19, 45, 0),
    text: "这是一个线上活动",
    name: "吃饭睡觉打豆豆Online",
    activityType: '类型2',
    conferenceUrl: "www.baidu.com",
    isPlace: false,
    isCycle: false,
    isGroup: true, 
  },
  {
    id: 6,
    start: new Date(2023, 2, 25, 14, 45, 0),
    end: new Date(2023, 2, 25, 19, 45, 0),
    text: "这是一个活动",
    name: "吃饭睡觉打豆豆",
    activityType: '类型1',
    placeID: 1,
    isPlace: true,
    isCycle: true,
    isGroup: false,
  },
  {
    id: 7,
    start: new Date(2023, 2, 25, 14, 45, 0),
    end: new Date(2023, 2, 25, 19, 45, 0),
    text: "这是一个线上活动",
    name: "吃饭睡觉打豆豆Online",
    activityType: '类型2',
    conferenceUrl: "www.baidu.com",
    isPlace: false,
    isCycle: false,
    isGroup: true, 
  },
  {
    id: 8,
    start: new Date(2023, 2, 25, 14, 45, 0),
    end: new Date(2023, 2, 25, 19, 45, 0),
    text: "这是一个活动",
    name: "吃饭睡觉打豆豆",
    activityType: '类型1',
    placeID: 1,
    isPlace: true,
    isCycle: true,
    isGroup: false,
  },
  {
    id: 9,
    start: new Date(2023, 2, 25, 14, 45, 0),
    end: new Date(2023, 2, 25, 19, 45, 0),
    text: "这是一个线上活动",
    name: "吃饭睡觉打豆豆Online",
    activityType: '类型2',
    conferenceUrl: "www.baidu.com",
    isPlace: false,
    isCycle: false,
    isGroup: true, 
  },
]