export const mockActivityData = [
  {
    id: 0,
    time: new Date(),
    place: "学生发展中心",
    type: "电竞",
    name: "The Binding of Issac 锦标赛",
  },
  {
    id: 1,
    time: new Date("2023-04-05"),
    place: "主楼 902",
    type: "八卦",
    name: "梁宸恋爱史分享会",
  },
  {
    id: 2,
    time: new Date(),
    place: "学五 1314",
    type: "桌游",
    name: "三国杀身份军争八人场",
  },
  {
    id: 5,
    time: new Date("2023-04-05"),
    place: "主楼 902",
    type: "八卦",
    name: "章成文研究生保送到耶鲁大学分享会",
  },
  {
    id: 6,
    time: new Date(),
    place: "学五 1314",
    type: "桌游",
    name: "狼人杀八人场狼人杀八人场狼人杀八人场狼人杀八人场",
  },
  {
    id: 8,
    time: new Date("2023-04-05"),
    place: "主楼 902",
    type: "八卦",
    name: "章成文研究生保送到耶鲁大学分享会",
  },
  {
    id: 9,
    time: new Date(),
    place: "学五 1314",
    type: "桌游",
    name: "狼人杀八人场",
  },
];
